spring:
  datasource:
    url: jdbc:mysql://localhost:57693/sis_financeiro_receita?createDatabaseIfNotExist=true
    username: root
    password: ${USER_PASSWORD:root}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
