server:
  port: 8081

spring:
  application:
    name: receita-ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}