spring:
  datasource:
    url: jdbc:mysql://localhost:57693/sis-financeiro-receita?createDatabaseIfNotExist=true
    username: root
    password: ${USER_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
